### ISSUE TITLE
 Intent to relicense under MIT license

### ISSUE THREAD

**Issue by djzort** [mrproper/proxmox-ve-api-perl#11]
See also https://en.wikipedia.org/wiki/MIT_License and https://metacpan.org/pod/Software::License::MIT

Contributors need to sign off:

@mrproper yes
@dpiquet yes (via email)
@pmorch yes
@ebl yes (via email)
@sauriol n/a (code replaced)
@manwar yes
@japp-0xlabs n/a (change was reverting prior changes)
@p5i yes (via email)

**Comment by pmorch** [comment]
I'm happy to relicense whatever I've contributed to be used under an MIT license. 

What else would you like me to do?

**Comment by manwar** [comment]
No objection from me, too.

**Comment by mrproper** [comment]
No objections from me

**Comment by djzort** [comment]
v0.36 is released as MIT
